image: maven:latest

stages:
  - build
  - test
  - package

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  tags:
    - maven
  script:
    - mvn $MAVEN_CLI_OPTS compile
  artifacts:
    expire_in: 30 min
    paths: 
      - target/

test:
  stage: test
  tags:
    - maven
  script:
    - rm target/surefire-reports/TEST-*.xml
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

package:
  stage: package
  tags:
    - maven
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.test.skip package
  artifacts:
    paths:
      - target/*.jar
